import { useEffect, useState } from "react";
import { RefreshCw, Sparkles } from "lucide-react";

import { clearCachedSummary, generateAiSummary } from "@/lib/gemini";
import type { ScanRecord } from "@/lib/types";

interface AiSummaryProps {
  scan: ScanRecord;
}

const AiSummary = ({ scan }: AiSummaryProps) => {
  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [refreshKey, setRefreshKey] = useState(0);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    setSummary(null);

    generateAiSummary(scan)
      .then((text) => {
        if (!cancelled) {
          setSummary(text);
          setLoading(false);
        }
      })
      .catch((err: unknown) => {
        if (!cancelled) {
          const message = err instanceof Error ? err.message : "unknown";
          console.error("[AiSummary] failed:", message, err);
          setError(message);
          setLoading(false);
        }
      });

    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [scan.id, refreshKey]);

  const handleRefresh = () => {
    clearCachedSummary(scan.id);
    setRefreshKey((key) => key + 1);
  };

  const isNoKey = error === "no_key";
  const isTimeout = error === "request_timeout";
  const apiParts = error?.startsWith("api_error:") ? error.split(":") : null;
  const apiStatus = apiParts?.[1] ?? null;
  const apiBody = apiParts?.slice(2).join(":") ?? null;
  const apiBodyLower = apiBody?.toLowerCase() ?? "";
  const hasQuotaError = apiStatus === "429" && (apiBodyLower.includes("quota") || apiBodyLower.includes("billing"));
  const errorHint =
    isTimeout
      ? "Gemini took too long to respond. Retry in a moment."
      : apiStatus === "400" || apiStatus === "403"
        ? `API key invalid or not authorised (HTTP ${apiStatus}). Check VITE_GEMINI_API_KEY.`
        : hasQuotaError
          ? "Gemini quota is exhausted for this API key. Check billing and quota, or switch to a model this key can access."
          : apiStatus === "429"
            ? "Rate limit reached - wait a moment then retry."
            : apiStatus
              ? `Gemini returned HTTP ${apiStatus}${apiBody ? `: ${apiBody}` : ""}`
              : `Request failed: ${error}`;

  return (
    <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-card">
      <div className="flex items-center gap-[8px] border-b border-border bg-primary/5 px-[16px] py-[12px]">
        <Sparkles size={14} className="text-primary" />
        <span className="text-[11px] font-semibold uppercase tracking-wider text-primary">AI Summary</span>
        {!loading && !isNoKey && (
          <button
            onClick={handleRefresh}
            title="Regenerate summary"
            className="ml-auto text-muted-foreground transition-colors hover:text-foreground"
          >
            <RefreshCw size={13} />
          </button>
        )}
      </div>

      <div className="p-[16px]">
        {loading && (
          <div className="space-y-[8px]">
            <div className="h-[13px] animate-pulse rounded-full bg-secondary" />
            <div className="h-[13px] w-[88%] animate-pulse rounded-full bg-secondary" />
            <div className="h-[13px] w-[72%] animate-pulse rounded-full bg-secondary" />
          </div>
        )}

        {!loading && isNoKey && (
          <p className="text-sm text-muted-foreground">
            Add a <code className="rounded bg-secondary px-[4px] py-[2px] text-xs">VITE_GEMINI_API_KEY</code> to your{" "}
            <code className="rounded bg-secondary px-[4px] py-[2px] text-xs">.env</code> file to enable AI summaries.
          </p>
        )}

        {!loading && !isNoKey && error && (
          <div className="flex items-center justify-between gap-[8px]">
            <p className="text-sm text-muted-foreground">{errorHint}</p>
            <button
              onClick={handleRefresh}
              className="shrink-0 rounded-lg bg-secondary px-[10px] py-[6px] text-xs font-medium text-foreground"
            >
              Retry
            </button>
          </div>
        )}

        {!loading && summary && (
          <>
            <p className="text-sm leading-relaxed text-foreground">{summary}</p>
            <p className="mt-[10px] text-[11px] text-muted-foreground">Generated by Gemini - For reference only, not medical advice</p>
          </>
        )}
      </div>
    </div>
  );
};

export default AiSummary;
